"""
Django settings for backendD project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from django.conf import settings
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q(#tia376$n+1ugieitp!znvus1!!q0v(vz#(-da5m&ot!w53y'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True


ALLOWED_HOSTS = ["*", "192.168.1.3", "localhost","192.168.68.110"]

DEBUG = True



from datetime import timedelta
# Application definition
AUTH_USER_MODEL = 'backend.User'

SIMPLE_JWT = {
    "USER_ID_FIELD": "autonum",    # Must be the actual database PK field
    "USER_ID_CLAIM": "user_id",    # Claim stored in JWT
    "AUTH_HEADER_TYPES": ("Bearer",),
}
AUTHENTICATION_BACKENDS = [
    'backend.auth_backend.CustomUserBackend',  # Adjust path
]

INSTALLED_APPS = [
    'django_user_agents',
    'daphne',
    'backend',
    'channels',
    'channels_redis',
    # 'django.contrib.admin',
    'django_extensions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Add this line for Django REST Framework
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
  
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
     'django_user_agents.middleware.UserAgentMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #   'backend.middleware.ThreadLocalMiddleware',
    
]

ROOT_URLCONF = 'backendD.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}
WSGI_APPLICATION = 'backendD.wsgi.application'
ASGI_APPLICATION = 'backendD.asgi.application'
CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_ALLOW_ALL = True


# ****** FOR DEVELOPMENT SETUP *****
# SESSION_COOKIE_SAMESITE = "Lax"
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SAMESITE = "Lax"
# CSRF_COOKIE_SECURE = False
# JWT_COOKIE_SECURE = False
# JWT_COOKIE_SAMESITE = "Lax"

# ****** FOR PRODUCTION SETUP *****
JWT_COOKIE_SECURE = True
JWT_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"   # allow cross-site (important for HTTPS + frontend)
SESSION_COOKIE_SECURE = True       # cookies sent only over HTTPS
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True


CORS_ALLOW_ORIGIN_REGEX = r'^https?://\w+(\.\w+)+(:\d{1,5})?$'  # Regex to match origins
# CORS_ALLOW_HEADERS = ['Content-Type', 'Authorization']  # Allowed headers
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'] 
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'backend.auth.authentication.CookieJWTAuthentication',  # Your custom cookie handler
#         'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback
#     ),
# }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "backend.auth.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    )
}


# JWT_COOKIE_SECURE = not DEBUG         # True in prod, False in dev
# JWT_COOKIE_SAMESITE = "None" if JWT_COOKIE_SECURE else "Lax"

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

APPEND_SLASH = False
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "X-CSRFToken",
    "Content-Disposition",  # Important for downloads
]
CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOWED_ORIGINS = ["app://.", "file://","http://localhost:5173","http://localhost:3000","http://192.168.137.1:3000"]  # adjust for your frontend


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "app://.",
    "file://",
    "http://192.168.68.110:3000",
    "http://192.168.68.110:19000",  # Your Expo dev server
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^app://.*$",
    r"^file://.*$",
    r"^http://localhost.*$",
    r"^http://192\.168\.1\.3.*$",
    r"^http://192\.168\.68\.110.*$"
]

CSRF_TRUSTED_ORIGINS = ["http://localhost:3000", "app://.","http://192.168.68.110:3000"]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_gerry_bels2Q25v2',
        'USER': 'root',
        'PASSWORD': 'lsi2010',
        'HOST': '192.168.68.110',  # Use the service name
        'PORT': '3309'    # MySQL default port

    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'



USE_I18N = True

USE_TZ = True
TIME_ZONE = 'Asia/Manila'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = '/home/galigao/backendD_media' # Folder for media files in WSL
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'