version: '3.8'

services:
  db:
    container_name: database
    image: mysql:8.2.0
    ports:
      - "3306:3307"
    environment:
      MYSQL_DATABASE: db_restaurant
      MYSQL_ROOT_PASSWORD: lsi2010  # Set the root password here
      MYSQL_PORT: 3307 
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    extra_hosts:
      - host.docker.internal:host-gateway
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SECRET_KEY=django-insecure-q(#tia376$n+1ugieitp!znvus1!!q0v(vz#(-da5m&ot!w53y  # Set your Django secret key here
volumes:
  mysql_data:
