version: '3'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/BackendD
    command: bash -c "daphne -b 0.0.0.0 -p 8001 BackendD.asgi:application & python manage.py runserver 0.0.0.0:8000"
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: lsi2010
      MYSQL_DATABASE: db_restaurant
    networks:
      - mynetwork

networks:
  mynetwork:
